# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog de Son Link
email: sonlink.dourden@gmail.com
description: > # Mi blog personal donde hablo de mis proyectos, tutoriales, etc, ademas de exponer mis trabajos y proyectos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://son-link.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#theme: jekyll-theme-space
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Social Network
social_links: true # If true show social links
rss: true
facebook: 'https://www.facebook.com/Son-Link-Blog-159172270839305/?ref=your_pages'
twitter: 'https://twitter.com/sonlink'
github: 'https://github.com/son-link'
instant_view: d2c6ec48864ff3 #Hash for Telegram Instant View
# Pagination
paginate: 10
paginate_path: "page:num/"

disqus: blogdesonlink
google-analytics: UA-75229203-1
related_posts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - borradores/
