title: Blog de Son Link
email: sonlink.dourden@gmail.com
description: > # Mi blog personal donde hablo de mis proyectos, tutoriales, etc, ademas de exponer mis trabajos y proyectos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://son-link.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#theme: jekyll-theme-space
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Social Network
social_links: true # If true show social links
rss: true
facebook: 'https://www.facebook.com/Son-Link-Blog-159172270839305/?ref=your_pages'
twitter: 'https://twitter.com/sonlink'
github: 'https://github.com/son-link'
instant_view: d2c6ec48864ff3 #Hash for Telegram Instant View
# Pagination
paginate: 10
paginate_path: "page:num/"

disqus: blogdesonlink
google-analytics: UA-75229203-1
related_posts: true
include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - borradores/
